version: '3.8'

# Simplified Docker Compose for testing and quick deployment
# Use this if the full production setup has issues

services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ai-service-simple
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DEBUG=false
      - WORKERS=2
      # Disable Elasticsearch initially for testing
      - ENABLE_ELASTICSEARCH_AUTH=false
      - ENABLE_SEARCH=false
      - ENABLE_SEARCH_CACHE=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional Elasticsearch (can be started separately)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-simple
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_simple_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    profiles:
      - with-search

volumes:
  elasticsearch_simple_data:
    driver: local