global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@example.com'
  smtp_auth_username: 'alerts@example.com'
  smtp_auth_password: 'password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      group_interval: 5s
      repeat_interval: 30m
    
    # Warning alerts - delayed notification
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 2h
    
    # Info alerts - daily summary
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      group_interval: 5m
      repeat_interval: 24h

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://webhook:5001/webhook'
        send_resolved: true
        title: 'Search Integration Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@example.com'
        subject: '🚨 CRITICAL: Search Integration Alert'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ if .Annotations.runbook_url }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}
        headers:
          X-Priority: '1'
    webhook_configs:
      - url: 'http://webhook:5001/webhook'
        send_resolved: true
        title: '🚨 CRITICAL: Search Integration Alert'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.service }}
          **Component:** {{ .Labels.component }}
          **Instance:** {{ .Labels.instance }}
          **Time:** {{ .StartsAt }}
          {{ if .Annotations.runbook_url }}
          **Runbook:** {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@example.com'
        subject: '⚠️ WARNING: Search Integration Alert'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ if .Annotations.runbook_url }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}
    webhook_configs:
      - url: 'http://webhook:5001/webhook'
        send_resolved: true
        title: '⚠️ WARNING: Search Integration Alert'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.service }}
          **Component:** {{ .Labels.component }}
          **Instance:** {{ .Labels.instance }}
          **Time:** {{ .StartsAt }}
          {{ if .Annotations.runbook_url }}
          **Runbook:** {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}

  - name: 'info-alerts'
    email_configs:
      - to: 'team@example.com'
        subject: 'ℹ️ INFO: Search Integration Alert'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ if .Annotations.runbook_url }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}

  # Slack integration (optional)
  - name: 'slack-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#search-alerts'
        title: 'Search Integration Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Component:* {{ .Labels.component }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt }}
          {{ if .Annotations.runbook_url }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}
        send_resolved: true

  # PagerDuty integration (optional)
  - name: 'pagerduty-alerts'
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: '{{ .GroupLabels.alertname }}'
        details:
          summary: '{{ .Annotations.summary }}'
          description: '{{ .Annotations.description }}'
          severity: '{{ .Labels.severity }}'
          service: '{{ .Labels.service }}'
          component: '{{ .Labels.component }}'
          instance: '{{ .Labels.instance }}'
          time: '{{ .StartsAt }}'
          {{ if .Annotations.runbook_url }}
          runbook: '{{ .Annotations.runbook_url }}'
          {{ end }}

inhibit_rules:
  # Inhibit warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'component']
  
  # Inhibit info alerts when warning or critical alerts are firing
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'service', 'component']
  
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'info'
    equal: ['alertname', 'service', 'component']
