search:
  elasticsearch:
    hosts:
      - "http://localhost:9200"
    username: null
    password: null
    api_key: null
    verify_certs: false
    ca_certs: null
    timeout: 10
    max_retries: 3
    retry_on_timeout: true
    healthcheck_path: "/_cluster/health"
    smoke_test_timeout: 5
    default_index: "watchlist"
    ac_index: "watchlist_ac"
    vector_index: "watchlist_vector"
  ac_search:
    boost: 1.2
    fuzziness: 1
    min_score: 0.6
    field_weights:
      normalized_text: 2.0
      aliases: 1.5
      legal_names: 1.8
      original_text: 1.0
  vector_search:
    boost: 1.0
    min_score: 0.5
    ef_search: 100
    vector_field: "dense_vector"
    vector_dimension: 384
    similarity_type: "cosine"
    similarity_threshold: 0.7
    max_candidates: 1000
    enable_reranking: true
